### ISSUE TITLE
Error creating bean with name 'serverConfig' defined in class path resource [init-database.xml]: Cannot create inner bean 'com.avaje.ebean.config.AutofetchConfig#2e385cce' of type [com.avaje.ebean.config.AutofetchConfig] while setting bean property 'autofetchConfig'

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-spring#5]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serverConfig' defined in class path resource [init-database.xml]: Cannot create inner bean 'com.avaje.ebean.config.AutofetchConfig#2e385cce' of type [com.avaje.ebean.config.AutofetchConfig] while setting bean property 'autofetchConfig'; nested exception is org.springframework.beans.factory.CannotLoadBeanClassException: Cannot find class [com.avaje.ebean.config.AutofetchConfig] for bean with name 'com.avaje.ebean.config.AutofetchConfig#2e385cce' defined in class path resource [default-ebean-server.xml]; nested exception is java.lang.ClassNotFoundException: com.avaje.ebean.config.AutofetchConfig
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:313) ~[spring-beans-4.1.7.RELEASE.jar:4.1.7.RELEASE]
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:122) ~[spring-beans-

**Comment by rbygrave** [comment]
This issue is due to the later version of Ebean refactoring the AutofetchConfig to be AutoTuneConfig.

The fix is really to remove that part of the configuration from the default-ebean-server.xml configuration.
